### ISSUE TITLE
Loss of Aim in 4-Player Matches

### ISSUE THREAD

**Issue by Zection6V** [ag-advania/melonPrimeDS#1]
the perfect thing to fix would be the loose of aim when we are playing with 4 players
this is due to instable CPU cycles
the AIM memory write get missed

maybe adding a automatic check if AIM is working
but this is hard to reproduce
even with 4 players i wasn't able to reproduce it

maybe because they weren't moving or shooting in the same time
when you play with 4 players sometimes the AIM got stuck

and you have to press "E" to release it

this is because of slowdown of the game
and since all functions are working with CPU cycles (every 2 frames)
with slowdown it can break the cycle and the function may not work

4人プレイ時に発生する「照準がずれる」問題を解決する必要があります。
これはCPUサイクルの不安定さが原因で、AIMメモリへの書き込みが失敗するためです。

AIMが正常に動作しているかを自動でチェックする機能を追加するのも一案ですが、再現が難しいです。
実際、4人プレイでも全員が同時に移動したり射撃したりしない場合は再現できないことがあります。

4人プレイ中、時々AIMが動かなくなり、「E」キーを押して解除する必要が出ることがあります。
これはゲームの遅延が原因で、すべての機能がCPUサイクル（2フレームごと）に依存しているため、遅延によりサイクルが崩れ、機能が正常に動作しなくなることが考えられます。

**Comment by Zection6V** [comment]
I think it's fixed now, need more testers

**Comment by ag-advania** [comment]
We can close, no issues after asking for feedback for a prolonged 4 players games
