### ISSUE TITLE
When in "Even" or "Hybrid" view, spamming left clic and moving crosshair make bad AIM inputs

### ISSUE THREAD

**Issue by ag-advania** [ag-advania/melonPrimeDS#53]
Video:
https://github.com/user-attachments/assets/fc4fed48-766c-4329-a077-fb689bc0e561

Potential solution: 
Change mouse from "windowCenter" to "topscreenCenter"

**Comment by TrochiFranco** [comment]
oh i discover if you try playing on window it solves and this dont happen

**Comment by Zection6V** [comment]
fixed:
When the Screen-Layout is set to 'Natural' and clicking and aiming are performed quickly, the aim may jitter vertically.
